export const GET_COIN_DATA_STARTED = 'GET_COIN_DATA_STARTED';
export const GET_COIN_DATA_COMPLETE = 'GET_COIN_DATA_COMPLETE';
export const GET_COIN_DATA_ERROR = 'GET_COIN_DATA_ERROR';

export const SAVE_COIN_SYMBOLS = 'SAVE_COIN_SYMBOLS';
export const SAVE_FIAT_SYMBOLS = 'SAVE_FIAT_SYMBOLS';