export const GET_COIN_DATA = 'GET_COIN_DATA';
export const GET_COIN_DATA_STARTED = 'GET_COIN_DATA_STARTED';
export const GET_COIN_DATA_COMPLETE = 'GET_COIN_DATA_COMPLETE';
export const GET_COIN_DATA_ERROR = 'GET_COIN_DATA_ERROR';