
export var fiatTypes = [
        {value: "USD", label: "US Dollar"},
        {value: "BRL", label: "Brazilian Real"},
        {value: "AUD", label: "Australian Dollar"},
        {value: "CAD", label: "Canadian Dollar"},
        {value: "CHF", label: "Swiss Francs"},
        {value: "CLP", label: "Chilean Peso"},
        {value: "CNY", label: "Chinese Yuan"},
        {value: "CZK", label: "Czech Koruna"},
        {value: "DKK", label: "Danish Krone"},
        {value: "EUR", label: "Euro"},
        {value: "GBP", label: "British Pound"},
        {value: "HKD", label: "Hong Kong Dollar"},
        {value: "HUF", label: "Hungarian Forint"},
        {value: "IDR", label: "Indonesian Rupiah"},
        {value: "ILS", label: "Israeli New Shekel"},
        {value: "INR", label: "Indian Rupee"},
        {value: "JPY", label: "Japanese Yen"},
        {value: "KRW", label: "South Korean Won"},
        {value: "MXN", label: "Mexican Peso "},
        {value: "MYR", label: "Malaysian Ringgit"},
        {value: "NOK", label: "Norwegian Krone"},
        {value: "NZD", label: "New Zealand Dollar "},
        {value: "PHP", label: "Philippine Piso"},
        {value: "PKR", label: "Pakistani Rupee"},
        {value: "PLN", label: "Polish Zloty"},
        {value: "RUB", label: "Russian Ruble"},
        {value: "SEK", label: "Swedish Krona"},
        {value: "SGD", label: "Singapore Dollar"},
        {value: "THB", label: "Thai Baht"},
        {value: "TRY", label: "Turkish Lira"},
        {value: "TWD", label: "New Taiwan Dollar"},
        {value: "ZAR", label: "South African Rand"}
] ;

